version: 0.0
os: linux
files:
  - source: /build_output
    destination: /var/www/helloworld
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

